### ISSUE TITLE
cannot execute binary file: Exec format error

### ISSUE THREAD

**Issue by leecollings** [daibach142/SaitekRadio#2]
Trying to get this working on Raspberry Pi, but when i try to run the command `saitekradio`, I get the following response:

`bash: /usr/games/saitekradio: cannot execute binary file: Exec format error`

I have no idea what this means though... is there a simpler way of doing this by running a script file?

**Comment by leecollings** [comment]
Turns out it's because of the ARM architecture of Raspberry Pi, which this doesn't work with I take it?

Does this mean this will not work for Raspberry Pi?

**Comment by webknjaz** [comment]
@leecollingsco I would expect it to work if you compile for said architecture.

**Comment by daibach142** [comment]
Hi Lee & Sviatoslav
Yes, Sviatoslav is absolutely right - the Raspberry Pi installation needs to be done using the ./config/make/make install sequence on the Pi (for testing, maybe not the 'make install' step, as that sets the Pi into headless mode). 

Sorry - see next comment!!!!!!!!!!!!!!

Dave

**Comment by daibach142** [comment]
Sorry - my misunderstanding!!! I was commenting on the [https://github.com/daibach142/FGFS_Saitek_Radio](url), not on this product. This one was never intended/tested to run on the Raspberry Pi, although it may well do that if Rust is installed.

**Comment by daibach142** [comment]
Compiles and runs on Pi - screenshot of compilation etc. 
Don't have the panel available at the moment!
![Screenshot from 2023-06-08 01-57-21](https://github.com/daibach142/SaitekRadio/assets/8496367/78d6f8a8-09c5-4ba3-8ec3-80a59d3f92c5)

**Comment by leecollings** [comment]
Hi Dave,

Thanks for that, although in this straight away you're using a 'cargo' command - which is never mentioned in any of the documentation that I've read.

Could you update your documentation so it's clearer what needs to be done for Raspberry Pi users (As there seems to be very confusing / conflicting instructions between Windows and Linux / Raspberry Pi).

**Comment by daibach142** [comment]
Hi Lee
This product - [https://github.com/daibach142/SaitekRadio](url) - was never intended to be run on the Pi - hence no documentation about it. The original product - [https://github.com/daibach142/FGFS_Saitek_Radio](url) - had the Pi option as I was, at the time, unable to make a Windows-compatible version.

With the advent of the Rust language, a whole new range of target possibilities opened up, but I don't intend to document or support outside Linux/Windows. 

After your original problem with [https://github.com/daibach142/FGFS_Saitek_Radio](url), I updated that software to fix the compilation errors, and made a new release of that software.

Do you think we should close this issue?

Regards
Dave

**Comment by leecollings** [comment]
Hello Dave,

Please feel free to close any of my issues. I'[ll be open to admit, I'm not sure I follow everything that's been said to me.

I think I'm still going to have issues doing this with my Pi, as I don't believe it's compatible essentially.

But thank you so much for your help in what you've done so far trying to assist.

Appreciate it massively.

**Comment by daibach142** [comment]
Hi Lee
OK I'll close this issue here. The updated release of  [https://github.com/daibach142/FGFS_Saitek_Radio](url) - Version 1.3.0 - will work fine on your Pi. 

If you want to discuss about using the Pi, you can contact me directly - my email is : dave@attwoods.org.uk
